### PR TITLE
Add support for memory-mapped devices

### PR DESCRIPTION
**Pull request by SimonSapin**
This adds support for non-Intel architectures without "I/O ports" where a fw-cfg device is mapped into main memory instead. The base address needs to be passed as a parameter to a new constructor.

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’m fairly sure the new tests passed when I worked on this several months ago, but now I get the same failure as on CI and I don’t know what to try next :(

```
qemu-system-riscv32: -fw_cfg opt/input.txt,file=tests/input.txt: fw_cfg device not available
```

**Comment by CityAceE** [comment]
Could you create this issue on QEMU bug tracker?
https://gitlab.com/qemu-project/qemu/-/issues

**Comment by SimonSapin** [comment]
I believe this is the same as https://gitlab.com/qemu-project/qemu/-/issues/1343

**Comment by lion328** [comment]
Merged with #2.

**Pull request closed without merging**
